### ISSUE TITLE
[WP Silverlight 8.1] sqlite3 was not found

### ISSUE THREAD

**Issue by fravezzimattia** [ericsink/SQLitePCL.raw#83]
PROJECT:
**Xamarin Windows phone Silverlight 8.1**
LIBRARY:
**sqllite-net-pcl
SqlitePCL.bundle_green
SqlLitePCL.cppinterop**

ERROR:
\SQLitePCL.cppinterop.0.9.2\build\native\sqlite3\v120\x86\sqlite3.dll  because it was not found
	

doesn't exist the folder!! Why?

**Comment by ericsink** [comment]
Hmmm.  That's not good.  I'll look into it.

**Comment by ericsink** [comment]
Yup, that's a bug.  Support for Windows Phone Silverlight is currently rather screwed up.  I'll get a fix as soon as I can.

**Comment by ericsink** [comment]
But I should admit that "as soon as I can" now looks like at least 2 weeks away, due to some previous commitments.  :-(

**Comment by ripoljorge** [comment]
Hi Eric,
First of all thanks for all your work. 
For more information, I'm facing the same issue with a Windows Phone 8.0 project. 
Wishing that you'd have time to take a look at it :)
Thanks so much,
Regards

**Comment by ericsink** [comment]
Update:  The fix for this is now in the repo, but not yet in a pushed nuget package.

**Comment by NicoVermeir** [comment]
any idea when the nuget package will be updated? I'm working on a customer project this week and I'm running into this issue.

thanks!

**Comment by ericsink** [comment]
Hopefully this week.

**Comment by ericsink** [comment]
0.9.3 is on nuget and should fix this

**Comment by ripoljorge** [comment]
Hi Eric,

I updated my nuget packages to 0.9.3 but the error is still appearing while compiling my WP8 project.

> Could not copy the file "D:\xxx\packages\SQLitePCL.cppinterop.0.9.2\build\native\sqlite3\v110_wp80\x86\sqlite3.dll" because it was not found.			

I don't know if I'm missing something else, these are the nuget packages included in my project:

![image](https://cloud.githubusercontent.com/assets/20465107/17220782/10acf380-54f1-11e6-99a4-0ae7c7ba573a.png)

Thank you so much,

Kind regards

**Comment by ericsink** [comment]
Ooops.  Sorry.  You need to remove the SQLitePCL.cppinterop package.  It is not needed anymore.

**Comment by ripoljorge** [comment]
Hehe just removed it seconds ago after reviewing new dependencies :) It's compiling now.

Thank you so much!
